# Generated by Django 4.0.3 on 2022-04-19 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('tipo', models.CharField(choices=[('SOCIAL', 'Social'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('NOTICIAS', 'Noticias'), ('ACADEMICO', 'Academico'), ('OPINION', 'Opinion'), ('COMERCIO', 'Comercio'), ('TECNOLOGIA', 'Tecnologia'), ('PRODUCTIVIDAD', 'Productividad'), ('TURISMO', 'Turismo')], default='SOCIAL', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=50)),
                ('calificacionPromedio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gradoVeracidadPromedio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('categorias', models.ManyToManyField(default=None, to='websites.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numReviews', models.IntegerField(default=0)),
                ('sumaCalificacion', models.IntegerField(default=0)),
                ('sumaVeracidad', models.IntegerField(default=0)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='DatosCategoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantReviews', models.IntegerField(default=0)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.categoria')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
            options={
                'unique_together': {('website', 'tipo')},
            },
        ),
    ]
