# Generated by Django 4.0.3 on 2022-04-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_remove_reviewmetadata_numreviewsoptparams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmetadata',
            name='numReviewsOptParams',
        ),
        migrations.RemoveField(
            model_name='reviewmetadata',
            name='sumaCalificacionDiseno',
        ),
        migrations.RemoveField(
            model_name='reviewmetadata',
            name='sumaCalificacionUsabilidad',
        ),
        migrations.RemoveField(
            model_name='website',
            name='calificacionDisenoPromedio',
        ),
        migrations.RemoveField(
            model_name='website',
            name='calificacionUsabilidadPromedio',
        ),
    ]
