# Generated by Django 4.0.3 on 2022-04-22 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_remove_reviewmetadata_numreviewsoptparams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscategoria',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
