# Generated by Django 4.0.3 on 2022-04-22 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_datoscategoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscategoria',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
        migrations.AlterField(
            model_name='datoscategoria',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
