# Generated by Django 4.0.3 on 2022-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_website_autor_website_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('NO CALIFICADO', 'No calificado'), ('SOCIAL', 'Social'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('ORGANIZACION', 'Organizacion'), ('ACADEMICO', 'Academico'), ('COMERCIO', 'Comercio'), ('TECNOLOGIA', 'Tecnologia'), ('PRODUCTIVIDAD', 'Productividad'), ('INVESTIGACION', 'Investigacion'), ('PERIODISMO', 'Periodismo')], default='NO CALIFICADO', max_length=50, primary_key=True, serialize=False),
        ),
    ]
