# Generated by Django 4.0.3 on 2022-05-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0010_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='resumen',
            field=models.CharField(default='', max_length=250),
        ),
    ]
