# Generated by Django 4.0.3 on 2022-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0011_website_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('NOT RATED', 'Not Rated'), ('SOCIAL', 'Social'), ('ENTERTAINMENT', 'Entertainment'), ('BUSINESS/ORG', 'Business/Org'), ('ACADEMIC', 'Academic'), ('SHOPPING', 'Shopping'), ('TECHNOLOGY', 'Technology'), ('PRODUCTIVITY TOOLS', 'Productivity Tools'), ('RESEARCH', 'Research'), ('NEWS', 'News')], default='NOT RATED', max_length=50, primary_key=True, serialize=False),
        ),
    ]
