# Generated by Django 4.0.3 on 2022-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0012_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
