# Generated by Django 4.0.3 on 2022-05-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0014_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
