# Generated by Django 4.0.3 on 2022-05-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0016_alter_website_calificacionpromedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='calificacionPromedio',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='website',
            name='disenoPromedio',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='website',
            name='gradoVeracidadPromedio',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='website',
            name='usabilidadPromedio',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
