# Generated by Django 4.0.3 on 2022-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0017_alter_website_calificacionpromedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
