# Generated by Django 4.0.3 on 2022-04-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipo', models.CharField(choices=[('FREE', 'Free'), ('SURFIER', 'Surfier')], default='FREE', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=100)),
                ('puntos', models.IntegerField(default=0)),
                ('fechaVencimiento', models.DateField(default=None, null=True)),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=254, null=True)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('fecha', models.DateTimeField()),
                ('gradoVeracidad', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('calificacionDiseno', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('calificacionUsabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('website', 'usuario')},
        ),
    ]
