# Generated by Django 4.0.3 on 2022-04-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='calificacionDiseno',
            field=models.DecimalField(null=True, decimal_places=2, max_digits=4, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='calificacionUsabilidad',
            field=models.DecimalField(null=True, decimal_places=2, max_digits=4, default=0),
        ),
    ]
