# Generated by Django 4.0.2 on 2022-03-04 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=254)),
                ('tipo', models.CharField(max_length=254)),
            ],
        ),
    ]
